apiVersion: v1
kind: Service
metadata:
  name: admingui-backend
  namespace: admingui
  labels:
    app: admingui-backend
spec:
  type: ClusterIP
  selector:
    app: admingui-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001