apiVersion: v1
kind: Service
metadata:
  name: admingui-controller
  namespace: admingui
  labels:
    app: admingui-controller
spec:
  type: ClusterIP
  selector:
    app: admingui-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080